namespace :custom_update do

  desc "Copy spanish translations to english translations"
  task import_translations: :environment do
    exit if ENV['SOURCE_COMMIT'].blank?
    importer = TranslationsImporter.new(ENV['SOURCE_COMMIT'],ENV['TARGET_COMMIT'])
    importer.process
  end

  desc "Testing"
  task update_pxd_project: :environment do
    current_user = User.find_by_email Rails.env.production? ? 'alexgr200@gmail.com' : 'admin@example.com'
    project_slug = Rails.env.production? ? 'proxio-developers' : 'pxd'
    @project = Project.find_from_slug!(project_slug)

    fr_targets = {
      'enter-account' => "Se connecter a mon compte",
      'register-me' => "M' Inscrire",
      'connect-dev' =>  "Connectez vos développements avec plus de 600,000 agents près a vous aider",
      'developer' =>  "",
      'developers' =>  "Développements",
      'connect-now' =>  "Connectez vous dès maintenant",
      'get-access-world' =>  "Accédez à plus de 50 pays à travers le monde",
      'work-agents-clients' =>  "Travailler avec des agents et clients situés dans le monde entier",
      'say-clients' =>  "Que disent nos clients?",
      'email-and-clients' =>  "Couriel ou dépliants de marketing disponibles dans la langue de chacun de vos clients",
      'all-your-proyects' =>  "Tout vos développements disponibles en 19 langues",
      'create-a-team' =>  "Créer une équipe multiculturelle avec des agents formés en tous types de spécialités et d 'expertise.",
      'enhance-your-team' =>  "Renforcez votre équipe",
      'proxio-ss-fb-app' =>  "Application Facebook Proxio SocialSearch",
      'turn-fb-solution' =>  "Faites de Facebook votre meilleur outil mondial de marketing!",
      'bring-your-brand' =>  "Promouvoir votre marque et interagir avec vos clients sur les réseaux sociaux.",
      'add-proy-to-fb' =>  "Exposer tous vos développements sur Facebook afin de générer des clients potentiels.",
      'make-proy-likes-twits' =>  "Participer à la conversation et engager vos clients à partager, publier, épingler et à tweeter vos annonces",
      'select-plan' =>  "Choisissez un plan, vous pouvez l' annuler à n'importe quel moment.",
      'all-in-your-px-account' =>  "Votre compte Proxio est sûr et protégé a tout moment.",
      'powered-by' =>  "Alimenté par: © 2013 Proxio -",
      'all-right-reserved' =>  "Tous droits réservés",
      'section-start' =>  "Démarrer votre Séssion",
      'wellcome-huge-net' =>  "Bienvenue au réseau d'agents le plus grand au monde",
      'email' =>  "Adresse électronique",
      'password' =>  "Mot de Passe",
      'remind-me' =>  "Garder en mémoire mes informations",
      'enter2-account' =>  "Se connecter à mon compte",
      'forgot-psw' =>  "Avez-vous oublié votre mot de passe?",
      'company-name' =>  "Nom d'entreprise",
      'confirmation' =>  "Confirmation",
      'psw-requirements' =>  "Le mot de passe doit contenir au moins 8 caractères contenant chiffres et lettres",
      'real-state-brokers' =>  "Courtiers d'immobilier",
      'home' =>  "Accueil",
      'net-developments' =>  "Recherche de Développements",
      'signed-in-successfully' =>  "Vous êtes bien connecté",
      'hi' =>  "Bonjour",
      'account' =>  "Compte",
      'profile' =>  "Profil",
      'exit' =>  "Quitter",
      'activities' =>  "",
      'activity-feed' =>  "Activité du réseau",
      'my-developments' =>  "Mes Développements",
      'sales-kit' =>  "KIT DE VENTES",
      'my-records' =>  "Mes Archives",
      'my-apps' =>  "Mes Applications",
      'profile-edition' =>  "Modifier mon profil",
      'your-public-profile' =>  "Ceci est le URL publique de votre profil' => ",
      'recommended-dev' =>  "Développements Recommendés",
      'see-more-activity' =>  "Voir plus d'activité",
      'days' =>  "jours",
      'updated-dev-info' =>  "Renseignements du développement actualisés",
      'updated-basic-info' =>  "Renseignements basiques actualisés",
      'updated-terms-condition' =>  "Termes et Conditions du développement actualisés",
      'added-section-content' =>  "a ajouté une section de contenu' => ",
      'updated-section-content' =>  "a actualisé une section de contenu' => ",
      'publish-new-image' =>  "a ajouté une nouvelle photo.",
      'publish-new-document' =>  "",
      'updated-document' =>  "a actualisé le document",
      'publish-new-price-document' =>  "a publié une nouvelle liste de tarifs",
      'publish-new-post' =>  "a publié une nouvelle mise en jour",
      'publish-new-map' =>  "a publié un nouveau plan de maison",
      'publish-new-video' =>  "a publié une nouvelle vidéo",
      'updated-video' =>  "a actualisé la video",
      'updated-map' =>  "a actualisé le plan de maison",
      'new-subscriber' =>  "a un nouveau souscripteur",
      'near-to' =>  "Près de",
      'month' =>  "mois",
      'visit-dev' =>  "Voir Développement",
      'see-map' =>  "Voir plan de localisation",
      'see-doc' =>  "Voir document",
      'see-profile' =>  "Voir profil",
      'see-video' =>  "Voir la vidéo",
      'what-r-u-looking' =>  "Que recherchez-vous?",
      'subscriptions' =>  "Abonnements",
      'subscriptions-request' =>  "Demande d'abonnements",
      'Search' =>  "Rechercher",
      'remove-subscription' =>  "Annuler l'abonnement",
      'select-to-print-or-send' =>  "Activez la case à cocher pour imprimer ou envoyer les développements .",
      'select' =>  "Sélectionner",
      'delete' =>  "Supprimer",
      'remark-dev' =>  "Développements sélectionnés",
      'send-dev' =>  "Envoyer Développements",
      'print' =>  "Imprimer",
      'development' =>  "Développement",
      'agent' =>  "Agent",
      'all' =>  "Tout",
      'edit' =>  "Modifier",
      'register-by' =>  "Enregistr par:",
      'proxio-Social-Search' => "Proxio SocialSearch",
      'featured-developments' => "Développements Sélectionnés",
      'about-us' => "A PROPOS DE NOUS",
      'team' => "équipe",
      'our-company' => "Notre Entreprise",
      'languajes' => "Langues",
      'our-specialities' => "Nos Spécialitées",
      'my-agent-team' => "Mon équipe de Conseillers",
      'add-new-agent' => "Ajouter un nouveau conseiller",
      'edit-profile' => "Modifier mon profil",
      'edit-image' => "Modifier l'image",
      'edit-cover-image' => "Modifier l'image de couverture",
      'edition-ended' => "Donnée actualisée",
      'full-name' => "Nom Complet",
      'company' => "Entreprise",
      'contact-email' => "Adresse électronique",
      'phone' => "Numéro de Téléphone",
      'slogan' => "Slogan",
      'example-especiality' => "Exemple: Spécialisé en appartements. Votre agent immobilier de confiance, etc.",
      'we-are-group' => "Nous sommes un groupe de personnes organisé et engagé envers votre propriété.",
      'write-company-desc' => "Veuillez décrire votre entreprise",
      'location' => "Emplacement:",
      'be-exact-with-pointer' => "Essayez d'être aussi précis que possible, vous pouvez déplacer le pointeur au bon endroit.",
      'english' => "anglais",
      'spanish' => "espagnol",
      'italian' => "italien",
      'french' => "français",
      'japanese' => "japonais",
      'select-your-skills' => "Veuillez selectionner vos capacités",
      'equestrian-properties' => "Propriétés équestres",
      'golf-properties' => "Propriétés de Golf",
      'luxury-homes' => "Maisons de luxe",
      'new-homes' => "Maisons neuves",
      'resort-second-homes' => "Resort & résidences secondaires",
      'retirement-properties' => "Propriétés de retraite",
      'vacation-properties' => "Propriétés de vacances",
      'other' => "Autre",
      'facebook' => "Facebook",
      'fb-copy-paste-url' => "Copiez et collez le URL de votre profil Facebook",
      'twiter' => "Twitter",
      'linkedin' => "Linkedin",
      'tw-copy-paste-url' => "Copiez et collez le URL de votre profil Twitter",
      'li-copy-paste-url' => "Copiez et collez le URL de votre profil LinkedIn",
      'profile-image' => "Photo de profil",
      'choose-file' => "choisir le fichier",
      'no-file-chosen' => "Aucun fichier choisi",
      'cover-image' => "Image de couverture:",
      'save' => "Sauvegarder",
      'save-and-continue' => "Sauvegarder et continuer",
      'cancel' => "Annuler",
      'profile-updated-successfully' => "Actualisation du profil réussi.",
      'update' => "Actualiser",
      'account-edit' => "Modifier compte",
      'current-psw' => "Mot de Passe actuel",
      'leave-blank-if-no-psw-change' => "Laissez ce champ vide si vous ne souhaitez pas changer votre mot de passe",
      'enter-current-pws' => "Veuillez composer votre mot de passe actuel pour confirmer les changements",
      'delete-my-account' => "Supprimer mon compte",
      'new-development' => "Nouveaux Développements",
      'my-agents' => "Mes agents",
      'my-subscriptors' => "mes abonnés",
      'requests' => "Mes Invitations",
      'my-clients' => "Mes clients",
      'general-message' => "Message General",
      'images' => "Images",
      'videos' => "Vidéos",
      'documents' => "Documents",
      'select-development' => "Sélectionner un développement",
      'publish' => "Publier",
      'any-dev-update' => "Avez vous a actualiser vos développements?",
      'title' => "Titre",
      'write-a-photo-title' => "Veuillez donner le titre de cette photo",
      'click-to-add-image' => "Veuillez appuyer pour ajouter l'image",
      'min-image-size-msj' => "(L'image doit être 1000px X 600px minimum, et sera utilisée dans tous les documents de marketing.)",
      'write-a-title' => "Introduire le titre",
      'url' => "URL",
      'write-url-video' => "Entrez l'adresse URL (YouTube ou Vimeo)",
      'write-doc-name' => "Veuillez donner un nom a votre document",
      'click-to-add-doc' => "Veuillez appuyer pour ajouter le document",
      'my-agents-team' => "Mon équipe",
      'external-agents' => "Agents Externes",
      'no-pending-requests' => "Vous n'avez aucune invitation en ce moment",
      'broker' => "Immobilier",
      'general-description' => "Description Générale",
      'prospects' => "clients potentiels",
      'buyer-name' => "Nom de l'Acheteur",
      'agent-name' => "Nom de l'Agent",
      'register-date' => "Date d'Inscription:",
      'delete-amenity-warning' => "êtes vous sûr de vouloir supprimer cette section?",
      'add-new-section' => "Ajouter section",
      'development-name' => "Nom du Développement:",
      'development-logo' => "Logo du Developement",
      'name-label' => "Nom",
      'contact-position' => "Poste de Travail",
      'location-help' => "Essayez d'être aussi précis que possible, vous pouvez déplacer le pointeur au bon endroit ».",
      'country-label' => "Pays",
      'state-label' => "Etat",
      'city-label' => "Ville",
      'street-label' => "Rue",
      'street-number-label' => "Nom de Rue",
      'zone-label' => "Zone",
      'locality-label' => "Colonie",
      'reference-label' => "Référence",
      'public-subscriptions' => "Souscriptions publiques",
      'profit-label' => "Commission",
      'profit-help-text' => "Veuillez spécifier le pourcentage de commission que vous donnez aux agents de ce développement",
      'categories-label' => "Catégories",
      'categories-help-text' => "Veuillez spécifier la catégorie, ou les catégories, correspondantes a ce dévelopement",
      'amenities-label' => "Équipements",
      'amenities-help-text' => "Veuillez sélectionner les équipments correspondants a ce development",
      'content-sections' => "Sections des matières" }

    targets = {
    'country-label' => "Country",
    'cover-image' => "Cover Image",
    'create-a-team' => "Create a multicultural team composed of agents with all types specialties and expertise.",
    'current-psw' => "Current password",
    days: "days",
    delete: "Delete",
    'delete-amenity-warning' => "Are you sure you want to delete this section?",
    'delete-my-account' => "Cancel account",
    developer: "Developer",
    developers: "Developers",
    development: "Development",
    'development-logo' => "Development Logo",
    'development-name' => "Name of Development",
    documents: "Documents",
    edit: "Edit",
    'edit-cover-image' => "Edit cover image",
    'edit-image' =>"Edit image",
    'edit-profile' =>"Edit profil",
    'edition-ended' =>"Information updated",
    'email' =>"Email",
    'email-and-clients' =>"Email or print marketing flyers available in the language of all your clients",
    'english' =>"English",
    'enhance-your-team' =>"Strengthen your team",
    'enter2-account' =>"Login to my account",
    'enter-account' =>"Login to my account",
    'enter-current-pws' =>"Please enter your current password to confirm changes",
    'equestrian-properties' =>"Equestrian properties",
    'example-especiality' =>"Example: Specializes in condos. Your trusted real estate agent, etc.",
    'exit' =>"Sign Out",
    'external-agents' =>"External Agents",
    'facebook' =>"Facebook:",
    'fb-copy-paste-url' =>"Copy and paste the url of your Facebook profile",
    'featured-developments' =>"FEATURED DEVELOPMENTS",
    'forgot-psw' =>"Did you forget your password?",
    'french' =>"French",
    'full-name' =>"Full Name",
    'general-description' =>"General Description",
    'general-message' =>"General Message",
    'get-access-world' =>"Gain access to more than 50 countries around the world",
    'golf-properties' =>"Golf properties",
    'hi' =>"Hi",
    'home' =>"HOME",
    'images' =>"Images",
    'italian' =>"Italian",
    'japanese' =>"Japanese",
    'languajes' =>"Languages",
    'leave-blank-if-no-psw-change' =>"Leave blank if you do not wish to change your password",
    'li-copy-paste-url' =>"Copy and paste the url of your Linkedin profile",
    'linkedin' =>"LinkedIn:",
    'locality-label' =>"Colony",
    'location' =>"Location:",
    'location-help' =>"Try to be as accurate as possible, you can move the pointer to the right place.",
    'luxury-homes' =>"Luxury homes",
    'make-proy-likes-twits' =>"Become part of the property conversation as clients share, post, pin and tweet your listings!",
    'min-image-size-msj' =>"(The image should be 1000px X 600px minimum, and will be used in ALL marketing material.)",
    'month' =>"month",
    'my-agent-team' =>"My Team of Advisors",
    'my-agents' =>"My agents",
    'my-agents-team' =>"My team",
    'my-apps' =>"My Applications",
    'my-clients' =>"My clients",
    'my-developments' =>"MY DEVELOPMENTS",
    'my-records' =>"My records",
    'my-subscriptors' =>"My Subscribers",
    'name-label' =>"Name",
    'near-to' =>"Close to",
    'net-developments' =>"Development Search",
    'new-development' =>"New developments",
    'new-homes' =>"New homes",
    'new-subscriber' =>"has a new subscriber",
    'no-file-chosen' =>"No file chosen",
    'no-pending-requests' =>"You have no pending requests",
    'other' =>"Other",
    'our-company' =>"Our Company",
    'our-specialities' =>"Our Specialties",
    'password' =>"Password",
    'phone' =>"Telephone number",
    'powered-by' => "Powered by: © 2013 Proxio -",
    'print' =>"Print",
    'profile' =>"Profile",
    'profile-edition' =>"Edit Profile",
    'profile-image' =>"Profile Picture",
    'profile-updated-successfully' =>"Profile Sucessfully Updated",
    'profit-help-text' =>"Please state the commission that you will give to agents for this development",
    'profit-label' =>"Commission",
    'prospects' =>"Potential clients",
    'proxio-Social-Search' =>"Proxio SocialSearch",
    'proxio-ss-fb-app' =>"Proxio SocialSearch Facebook app",
    'psw-requirements' =>"The password must contain at least 8 characters, containing both numbers and letters",
    'public-subscriptions' =>"Public Subscriptions",
    'publish' =>"Post",
    'publish-new-document' =>"",
    'publish-new-image' =>"Posted a new image",
    'publish-new-map' =>"posted a new plan",
    'publish-new-post' =>"posted a new update",
    'publish-new-price-document' =>"posted a new price list",
    'publish-new-video' =>"posted a new video",
    'real-state-brokers' =>"Real state brokers",
    'recommended-dev' =>"Recommended Developments",
    'reference-label' =>"Reference",
    'register-by' =>"Registered by:",
    'register-date' =>"Registered date:",
    'register-me' =>"Sign Up",
    'remark-dev' =>"Featured developments",
    'remind-me' =>"Remember Me",
    'remove-subscription' =>"Cancel subscription",
    'requests' =>"My Requests",
    'resort-second-homes' =>"Resort & second homes",
    'retirement-properties' =>"Retirement Properties",
    'sales-kit' =>"Sales Kit",
    'save' =>"Save",
    'save-and-continue' =>"Save and continue",
    'say-clients' =>"What do our clients say?",
    'Search' =>"Search",
    'section-start' =>"Start Session",
    'see-doc' =>"See document",
    'see-map' =>"Map Plan",
    'see-more-activity' =>"See more activity",
    'see-profile' =>"See profile",
    'see-video' =>"Watch video",
    'select' =>"Select",
    'select-development' =>"Please select a development",
    'select-plan' =>"Select a plan. You can cancel it at anytime.",
    'select-to-print-or-send' =>"Select the box to print or send developments",
    'select-your-skills' =>"Please select your strengths",
    'send-dev' =>"Send Development",
    'signed-in-successfully' =>"SIGNED IN SUCCESSFULLY.",
    'slogan' =>"Slogan",
    'spanish' =>"Spanish",
    'state-label' =>"State",
    'street-label' =>"Street",
    'street-number-label' =>"Name of Street",
    'subscriptions' =>"Subscriptions",
    'subscriptions-request' =>"Subscription requests",
    'team' =>"TEAM",
    'title' =>"Title",
    'turn-fb-solution' =>"Turn Facebook into your best marketing solution!",
    'tw-copy-paste-url' =>"Copy and paste the url of your Twitter profile",
    'twiter' =>"Twitter:",
    'update' =>"Update",
    'updated-basic-info' =>"Basic information updated",
    'updated-dev-info' =>"Development information Updated",
    'updated-document' =>"has updated the document",
    'updated-map' =>"updated the plan",
    'updated-section-content' =>"has updated a section of content",
    'updated-terms-condition' =>"Updated Terms and Conditions of developement",
    'updated-video' =>"updated the video",
    'url' =>"URL",
    'vacation-properties' =>"Vacation homes",
    'videos' =>"Videos",
    'visit-dev' =>"See Development",
    'we-are-group' =>"We are a group of people organized and committed to your property.",
    'wellcome-huge-net' =>"Welcome to the largest network of agents in the world",
    'what-r-u-looking' =>"What are you searching for?",
    'work-agents-clients' =>"Work with agents and clients located around the world",
    'write-a-photo-title' =>"Please provide name of photo",
    'write-a-title' =>"Write title",
    'write-company-desc' =>"Please describe your company",
    'write-doc-name' =>"Please name document",
    'write-url-video' =>"Enter the url address (YouTube or Vimeo)",
    'your-public-profile' =>"This is the public URL to your profile:",
    'zone-label' =>"Zone" }

    fr_targets.each do |i, k|
      @key = Key.find_from_slug!(i.to_s, @project.id.to_s) rescue nil

      if @key.nil?
        puts("Not found: #{i.to_s}")
        next
      end

      @translation = @key.translations.where(rfc5646_locale: 'fr').first!

      # Need to save true copy_was because assign_attributes will push back the cache
      @translation.freeze_tracked_attributes
      @translation.assign_attributes copy: k.to_s

      @translation.translator = current_user if @translation.copy_was != @translation.copy
      @translation.modifier = current_user

      if @translation.present?
        # the only thing that can be edited is copy, so optimize DB calls if this
        # is not a copy edit
        if @translation.copy_was != @translation.copy # copy_changed? can be true even if the copy wasn't changed...
          @translation.preserve_reviewed_status = current_user.reviewer?
          @translation.save
        else
          # if the current user is a reviewer, treat this as an approve action; this
          # makes tabbing through fields act as approval in the front-end
          if current_user.reviewer?
            @translation.reviewer                 = current_user
            @translation.approved                 = true
            @translation.preserve_reviewed_status = true
            @translation.save
          end
        end
      end
    end
  end
end